### PR TITLE
Undefined and different nameing to arguments and parameters.

### PR DESCRIPTION
**Pull request by joetjen**
Hi,

I did some small changes to always append `undefined` to the argument list, but not in the parameter list, thus ensuring `undefined` really is undefined inside the closure. Additionally when using an object for parameters, the key will be used in the argument list and the value (is the value is a string) will be used in the parameter list.

Let me know if you have any questions.

Jan

### CODE REVIEW

**Comment by jshcrowthe** [comment]
@joetjen Thanks for your contributions! Looks like there are some failing tests so if you can look into those while I look at your changes over the next couple days that'd be great!

**Comment by joetjen** [comment]
@jshcrowthe Fixed the test cases and added a new one. Sorry I hadn't noticed the failing tests before, should've checked before committing :anguished:

**Comment by jshcrowthe** [comment]
@joetjen Perfect! Thanks. I noticed a couple things that if you'll address I think we are good! 
- Changed all single quotes to double quotes (Is this a necessary change? I really don't care one way or another but it doesn't seem necessary)
- Added a lot of config files (You have added a whole host of files: `.jshintrc`, `.jshintignore`, `.gitattributes`, `.editorconfig`, etc) that I don't feel like we need. What's the reason behind these?

**Comment by joetjen** [comment]
The .jshint files are configuration files for JSHint, a JavaScript linter, to ensure the code style is the same across all files.

The .editorconfig is a configuration file supported by various editors to help apply formatting rules (like indention settings, etc.) automatically.

Last but not least the .gitattributes file ensure git handles files with the same line endings across all systems.

**Comment by joetjen** [comment]
I am closing this, since @jshcrowthe  seems not to be interested in pulling in the request and I've probably waited long enough.

**Comment by jshcrowthe** [comment]
@joetjen Sorry for the hold up on this! I have gone through and reviewed your changes and I have a couple comments that, if you'd be willing to address, then I'd love to merge this.
- config files: I appreciate your additions of the `.jshintrc`, `.editorconfig` as well as extending the `.gitignore`. I would probably want to develop my own `.jshintrc` (although I would use ESLint as it has been my go to linter now for a while) to ship with this and so I'd be happy to work on creating one of those in a separate issue/PR. However it doesn't seem relevant to this PR.
- Unnecessary line edits: I notice you favor use of double-quotes over single quotes (stylistic choice) and have replaced all of the existing single w/ double. IMO this isn't necessary and clutters the actual change.
- Commit tree: Lastly if you could [squash your commits](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) so we can keep the commit tree clean then I'd love to get this merged!

Thanks for your patience!

**Pull request closed without merging**
